initial commit add functionality
logzio/logzio-google-pubsub pull request #1
Opened 2022-10-26 08:30 UTC by resdenia

Integration includes cloud_function on go.
And ssh to run gcloud cloud build

2022-10-27 06:01 UTC, Doron-Bargo requested changes
Please go over my comments

2022-10-27 06:01 UTC, Doron-Bargo commented on README.md
> +-   clone repository to your computer
Why need to clone entire repo and not just the script itself as a release?

2022-10-27 06:01 UTC, Doron-Bargo commented on README.md
> +| REGION                            | Your AWS access key ID. \*`Requires for Deploy to Cloud option for platform`.                                                           |
Please go over the readme

2022-10-27 06:01 UTC, Doron-Bargo commented on run.sh
> +  stringarray=($line)
What happens if the customer don't put some of the parameters, where are all the validation processes?

2022-10-27 06:01 UTC, Doron-Bargo commented on config_txt.txt
> +{
Please change the name of the file

2022-10-27 06:01 UTC, Doron-Bargo commented on cloud_function_go/main.go
> +		logzio.SetDrainDuration(time.Minute*10),
Why draining the queue every 10 minutes?

2022-10-27 06:01 UTC, Doron-Bargo commented on run.sh
> +TOKEN=$2
What happens if some use a different order of the parameters

2022-10-30 08:03 UTC, Doron-Bargo requested changes
Good improvement
Please see my comments

2022-10-30 08:03 UTC, Doron-Bargo commented on README.md
> +Spin up your Docker containers if you haven’t done so already.
What docker?

2022-10-30 08:03 UTC, Doron-Bargo commented on README.md
> +1. Before start a proccess please be sure that is you logged in and you setup relevant project.
Please change to: "Please make sure you are logged in to the relevant project"

2022-10-30 08:03 UTC, Doron-Bargo commented on README.md
> +And need to have assigned to the project, Billing Account.
Why the customer need "Billing Account" permission?

2022-10-30 08:03 UTC, Doron-Bargo commented on README.md
> +6. Run a code with variables
Please change to: "Run the code with the following variables"

2022-10-30 08:03 UTC, Doron-Bargo commented on README.md
> +Spin up your Docker containers if you haven’t done so already.
Which docker does the customer need to spin up?

2022-10-30 08:03 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		logzio.SetinMemoryCapacity(24000000),
Why overriding the default values?

2022-10-30 08:03 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		logzio.SetlogCountLimit(6000000),
Why overriding the default values?

2022-10-30 08:03 UTC, Doron-Bargo commented on config.json
> +                "--source=gs://logzio-pubsub-handler/cloud_function.zip"
Why putting the function in Google storage and not aws s3

2022-10-30 08:03 UTC, Doron-Bargo commented on run.sh
> +	cmd_create_cloud_build="$(curl -X POST -T config.json -H "Authorization: Bearer $(gcloud config config-helper --format='value(credential.access_token)')" https://cloudbuild.googleapis.com/v1/project
Please move the access token to a parameters

2022-10-30 08:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "\033[0;31mrun.sh (1): Logz.io Type for logs must be specified\033[0;37m"
Why type must be specified and not use a default value in case its missing

2022-10-30 08:03 UTC, Doron-Bargo commented on config.json
> +            "args": ["-c", "gcloud pubsub topics create $_PUBSUB_TOPIC_NAME"]
What happen if it already exists?

2022-10-30 08:03 UTC, Doron-Bargo commented on config.json
> +                "gcloud logging sinks create $_SINK_NAME pubsub.googleapis.com/projects/$PROJECT_ID/topics/$_PUBSUB_TOPIC_NAME --log-filter=\"NOT (resource.type=\"cloud_function\" resource.labels.fun
What happens if it already exists?

2022-10-30 08:03 UTC, Doron-Bargo commented on config.json
> +                "gcloud alpha functions add-iam-policy-binding $_FUNCTION_NAME --region=$_REGION --member=allUsers --role=roles/cloudfunctions.invoker\n"
Why not dynamic name

2022-10-30 11:17 UTC, resdenia commented on README.md
> +And need to have assigned to the project, Billing Account.
Some of the old accounts can be created without assign Billing Account.

2022-10-30 11:21 UTC, resdenia commented on run.sh
> +        echo -e "\033[0;31mrun.sh (1): Logz.io Type for logs must be specified\033[0;37m"
Changing to optional

2022-10-30 11:23 UTC, resdenia commented on config.json
> +                "gcloud logging sinks create $_SINK_NAME pubsub.googleapis.com/projects/$PROJECT_ID/topics/$_PUBSUB_TOPIC_NAME --log-filter=\"NOT (resource.type=\"cloud_function\" resource.labels.fun
I removing it 
"gcloud logging sinks delete $_SINK_NAME || true",

2022-10-30 11:23 UTC, resdenia commented on config.json
> +            "args": ["-c", "gcloud pubsub topics create $_PUBSUB_TOPIC_NAME"]
I removed it in the previous step

2022-10-30 11:30 UTC, resdenia commented on config.json
> +                "--source=gs://logzio-pubsub-handler/cloud_function.zip"
Google provides 3 options to deploy from
```
--source=SOURCE
Location of source code to deploy.
Location of the source can be one of the following three options:

Source code in Google Cloud Storage (must be a .zip archive),
Reference to source repository* or,
Local filesystem path (root directory of function source).
```
*[repository](https://source.cloud.google.com/onboarding/welcome)

2022-10-30 19:26 UTC, Doron-Bargo requested changes
We are almost there. Please see my comments

2022-10-30 19:26 UTC, Doron-Bargo commented on README.md
> +| token        | The token of the account you want to ship to.                                                                                                                 |
The logs' shipping token

2022-10-30 19:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Println(err)
please add a message to the error

2022-10-30 19:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Println(err)
please add a message to the error

2022-10-30 19:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	if err != nil {
please add a message to the error

2022-10-30 19:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	if err != nil {
please add a message to the error

2022-10-30 19:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	"github.com/logzio/logzio-go"
I think it better to use your own http request instead of using this package as this one is too robust ( internal queue.. )  for sending logs

2022-10-30 19:26 UTC, Doron-Bargo commented on README.md
> +4. Assign a Billing Account to the selected project.
Why we need Billing Account?

2022-10-30 19:26 UTC, Doron-Bargo commented on README.md
> +1. Log in to your GCP account:
Please move step 1-3 to the prerequisites under - "Make sure you are connected to the relevant GCP project" and use html tag - details to expands the instruction on how to set it

2022-10-30 19:26 UTC, Doron-Bargo commented on run.sh
> +	echo -e "[INFO] [$(date +"%Y-%m-%d %H:%M:%S")] Populating data to json ..."
Please make sure the file is with the right indentation

2022-10-30 19:26 UTC, Doron-Bargo commented on run.sh
> +    # if [[ -z "$type" ]]; then
Please delete this part from the file if its not relevant anymore

2022-10-30 19:26 UTC, Doron-Bargo commented on run.sh
> +                    echo -e "\033[0;31mrun.sh (1): no Logz.io Listener URL specified!\033[0;37m"
Please change the message to a more informative one. Something like:
Logz.io Listener URL is missing please rerun the script with the relevant parameters.
Also please change for the other error messages

2022-11-02 07:05 UTC, Doron-Bargo requested changes
Good improvement. Please check my comment regrading the logzio-go, since it a serverless code I think we will have delay problems with it

2022-11-03 08:26 UTC, Doron-Bargo requested changes
Please see my comments

2022-11-03 08:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	backOff := time.Second * 2
Please add the following:
1. check size
2. gzip the message before sending

2022-11-03 08:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	for attempt := 0; attempt < sendRetries; attempt++ {
Please move to a different function

2022-11-03 08:26 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	token := r.URL.Query().Get("token")
please move the config and validation part to a different function
Also the validation should come immediate after the query get and not in the end

2022-11-03 19:56 UTC, Doron-Bargo requested changes
Please see my comments

2022-11-03 19:56 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		resp, err := http.Post(url, "application/json",
since you are sending gzip you should update the header accordingly

2022-11-03 19:56 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	if binary.Size(compressedBuf) > 10485760 {
please use a global parameter for the maximum size. Also you should check the size of the message before trying to compress it

2022-11-03 19:56 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	token := r.URL.Query().Get("token")
The "validateCheck" function can return the relevant parameters so you dont need to query them again

2022-11-03 20:02 UTC, Doron-Bargo requested changes

2022-11-03 20:02 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Printf("Got HTTP %d unauthorized, skip retry\n", statusCode)
If you get unauthorized its mean the token is incorrect . Let put more informative message

2022-11-06 12:28 UTC, Doron-Bargo requested changes
Almost there
Please check my comments

2022-11-06 12:28 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Printf("Got HTTP %d unauthorized, skip retry. Please check if you providing proper token or listner\n", statusCode)
Please check your Logs' Token and try again

2022-11-06 12:28 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	if binary.Size(compressedBuf) > maxSize {
If it bigger we should cut it
Also the size checking should be before trying to compress the buffer

2022-11-07 16:02 UTC, Doron-Bargo requested changes
small updates are needed

2022-11-07 16:02 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		cutMessage := string(rawDecodedText)[:middleCounter]
why to cut in the middle and not getting only the first 500kb ?

2022-11-07 16:02 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +const maxSize = 10485760
AFAIK the maximum for a single log is 500kb

2022-11-07 16:02 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Println("The request body size is larger than 10 MB.")
please use the parameter here

2022-11-08 11:27 UTC, Doron-Bargo approved these changes
lgtm

2022-11-08 11:54 UTC, merged