Function trigger
logzio/logzio-google-pubsub pull request #3
Opened 2022-12-25 15:53 UTC by resdenia

-Exclude function from cloud storage
-Change trigger from HTTP to Pubsub trigger

2023-01-03 10:45 UTC, Doron-Bargo requested changes
Please check my comments

2023-01-03 10:45 UTC, Doron-Bargo commented on run.sh
> +	topic_prefix="$function_name-pubsub-topic-logs-to-logzio"
Please fix indentation

2023-01-03 10:45 UTC, Doron-Bargo commented on config.json
> +        "_FUNCTION_NAME": "logzio_func_logzio",
why this name?
If it for logs why not
logzio_logs_function
Or something similar

2023-01-03 10:45 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	val, ok := m["textPayload"]
please use const parameters for "textPayload" and "severity" and

2023-01-03 10:45 UTC, Doron-Bargo commented on config.json
> +    "_LOGZIO_TOKEN": "vfFDZjscgjhUmUmhafqXaaTKBYNCZwpL",
Why you have private token inside public repo?

2023-01-03 10:45 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[INFO] [$(date +"%Y-%m-%d %H:%M:%S")] Project ID=$project_id where will launch integration."
Integration will be launch in Project ID=...

2023-01-09 12:07 UTC, Doron-Bargo requested changes
Please check my comments

2023-01-09 12:07 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Printf("Can't to parse json object: %s", err)
Can't update fields

2023-01-09 12:07 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		fmt.Printf("Can't parse to bytes: %s", err)
Can't parse json

2023-01-09 12:07 UTC, Doron-Bargo commented on cloud_function_go/function.go
>  		fmt.Printf("The request body size is larger than %d KB.", maxSize)
The request body size is larger than %d KB. We will cut the ...

2023-01-09 12:07 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +		req.Header.Add("logzio-shipper", "logzio-go/v1.0.0")
why you use this header ? its not logzio-go shipper

2023-01-09 12:07 UTC, Doron-Bargo commented on cloud_function_go/function.go
> +	logzioConfig.validation = true
what is this part?
Why you need to create this parameter and then call for the if
What is the other use case that this parameter will have false value?

2023-01-09 12:07 UTC, Doron-Bargo commented on config.json
> +        "_FUNCTION_NAME": "logzio_func_logzio",
The name is still not good

2023-01-09 12:07 UTC, Doron-Bargo commented on run.sh
> +    contents="$(jq --arg resource_list "${resource_list}" '.substitutions._FILTER_LOG = $resource_list' config.json)"
Please fix indentation

2023-01-09 13:08 UTC, resdenia commented on cloud_function_go/function.go
> +	logzioConfig.validation = true
I moved parameter to initialization of logzioConfig. And added to else statement to the if logic.

2023-01-10 10:33 UTC, Doron-Bargo requested changes
please check my comment

2023-01-10 10:33 UTC, Doron-Bargo commented on config.json
> +        "_FUNCTION_NAME": "dump_name_gcp_fucntion_name_func_logzio",
you are not using this parameter in your code

2023-01-10 11:01 UTC, Doron-Bargo approved these changes
lgtm

2023-01-10 11:47 UTC, merged