Support agent telemetry_list
logzio/logzio-google-pubsub pull request #8
Opened 2023-04-02 13:46 UTC by resdenia

In agent, we have the option `all_services`(to choose all the params from drop-down in Agent UI), in general integration, we don't have a such resource to monitor.

2023-04-02 13:54 UTC, resdenia commented on config.json
> -    "_LOGZIO_TOKEN": "vfFDZjscgjhUmUmhafqXaaTKBYNCZwpL",
test token was debprecated

2023-04-03 06:34 UTC, mirii1994 requested changes

2023-04-03 06:34 UTC, mirii1994 commented on README.md
>  ## Update log
```suggestion
## Changelog
```

2023-04-03 06:34 UTC, mirii1994 commented on README.md
> +**1.2.4**
```suggestion
- **1.2.4**
```
Make the version list a bullet list :)

2023-04-03 06:34 UTC, mirii1994 commented on config.json
> +    "steps": [
In this file only thing that was changed was the token?

2023-04-03 07:53 UTC, resdenia commented on config.json
> +    "steps": [
Rolled back to default values. Token, function name etc.

2023-04-03 08:04 UTC, mirii1994 approved these changes

2023-04-03 08:06 UTC, merged